services:
  postgres:
    image: postgres:latest
    container_name: csc13010-student-management-postgres
    restart: always
    environment:
      POSTGRES_DB: student_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      # - "./initdb:/docker-entrypoint-initdb.d"
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    container_name: csc13010-student-management-redis
    environment:
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      REDIS_POOL_SIZE: 10
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  connect:
    image: quay.io/debezium/connect:2.7
    container_name: csc13010-student-management-connect
    ports:
      - 8083:8083
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=kafka:29092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
      - postgres
    restart: always

  zookeeper:
    image: quay.io/debezium/zookeeper:2.7
    container_name: csc13010-student-management-zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: quay.io/debezium/kafka:2.7
    container_name: csc13010-student-management-kafka
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: always
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: csc13010-student-management-kafka-ui
    ports:
      - "9089:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=csc13010-student-management-kafka:29092
      # - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka

volumes:
  postgres_data:
  redis_data:
