// Code generated by MockGen. DO NOT EDIT.
// Source: internal/fileprocessor/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockIFileProcessingRepository is a mock of IFileProcessingRepository interface.
type MockIFileProcessingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIFileProcessingRepositoryMockRecorder
}

// MockIFileProcessingRepositoryMockRecorder is the mock recorder for MockIFileProcessingRepository.
type MockIFileProcessingRepositoryMockRecorder struct {
	mock *MockIFileProcessingRepository
}

// NewMockIFileProcessingRepository creates a new mock instance.
func NewMockIFileProcessingRepository(ctrl *gomock.Controller) *MockIFileProcessingRepository {
	mock := &MockIFileProcessingRepository{ctrl: ctrl}
	mock.recorder = &MockIFileProcessingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFileProcessingRepository) EXPECT() *MockIFileProcessingRepositoryMockRecorder {
	return m.recorder
}
