// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notification/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockINotificationUsecase is a mock of INotificationUsecase interface.
type MockINotificationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockINotificationUsecaseMockRecorder
}

// MockINotificationUsecaseMockRecorder is the mock recorder for MockINotificationUsecase.
type MockINotificationUsecaseMockRecorder struct {
	mock *MockINotificationUsecase
}

// NewMockINotificationUsecase creates a new mock instance.
func NewMockINotificationUsecase(ctrl *gomock.Controller) *MockINotificationUsecase {
	mock := &MockINotificationUsecase{ctrl: ctrl}
	mock.recorder = &MockINotificationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINotificationUsecase) EXPECT() *MockINotificationUsecaseMockRecorder {
	return m.recorder
}
