// Code generated by MockGen. DO NOT EDIT.
// Source: internal/faculty/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/csc13010-student-management/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIFacultyUsecase is a mock of IFacultyUsecase interface.
type MockIFacultyUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIFacultyUsecaseMockRecorder
}

// MockIFacultyUsecaseMockRecorder is the mock recorder for MockIFacultyUsecase.
type MockIFacultyUsecaseMockRecorder struct {
	mock *MockIFacultyUsecase
}

// NewMockIFacultyUsecase creates a new mock instance.
func NewMockIFacultyUsecase(ctrl *gomock.Controller) *MockIFacultyUsecase {
	mock := &MockIFacultyUsecase{ctrl: ctrl}
	mock.recorder = &MockIFacultyUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFacultyUsecase) EXPECT() *MockIFacultyUsecaseMockRecorder {
	return m.recorder
}

// CreateFaculty mocks base method.
func (m *MockIFacultyUsecase) CreateFaculty(ctx context.Context, faculty *models.Faculty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFaculty", ctx, faculty)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFaculty indicates an expected call of CreateFaculty.
func (mr *MockIFacultyUsecaseMockRecorder) CreateFaculty(ctx, faculty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFaculty", reflect.TypeOf((*MockIFacultyUsecase)(nil).CreateFaculty), ctx, faculty)
}

// DeleteFaculty mocks base method.
func (m *MockIFacultyUsecase) DeleteFaculty(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFaculty", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFaculty indicates an expected call of DeleteFaculty.
func (mr *MockIFacultyUsecaseMockRecorder) DeleteFaculty(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFaculty", reflect.TypeOf((*MockIFacultyUsecase)(nil).DeleteFaculty), ctx, id)
}

// GetFaculties mocks base method.
func (m *MockIFacultyUsecase) GetFaculties(ctx context.Context) ([]*models.Faculty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFaculties", ctx)
	ret0, _ := ret[0].([]*models.Faculty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFaculties indicates an expected call of GetFaculties.
func (mr *MockIFacultyUsecaseMockRecorder) GetFaculties(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFaculties", reflect.TypeOf((*MockIFacultyUsecase)(nil).GetFaculties), ctx)
}
